### ISSUE TITLE
Instruments Usage Error:  Ambiguous device name/identifier 'iPhone 6 Plus (9.0)'

### ISSUE THREAD

**Issue by bb-git** [fastlane/snapshot#198]
I always receive this error on running snapshot, for all languages, also for the iphone 6.

iphone 5 seems to run fine

**Comment by KrauseFx** [comment]
You could try resetting all your simulators using `snapshot reset_simulators`

**Comment by joepasq** [comment]
If you open Xcode's "Devices" window, it shows the installed simulators. My 6 and 6s are listed with paired Apple Watches, which changes the name of the simulator. 

I do not see a way to remove the watch simulator, my guess is that this is the cause of the problem. @KrauseFx is there a way to list the simulators that `snapshot` identifies?

**Comment by KrauseFx** [comment]
@joepasq `snapshot` creates one device per device type. I remember there was a way to fetch a list of available devices somewhere.

**Comment by joepasq** [comment]
Okay, thanks. @bb-git I was able to work around this by 1) opening the Devices window, 2) selecting iPhone 6, (then 6s) and hitting `enter`, or double-clicking the name in the sources-list/sidebar, and adding "- watch" to the name. 3) Then I added new simulators with just iPhone 6/6s.

**Comment by pedro380085** [comment]
Hi @KrauseFx , I've called `snapshot reset_simulators` and it did reset by simulators, but created iPhone 6 and iPhone 6 Plus twice. Don't know if that would be my configuration or is something related to snapshot.

**Comment by Ged2323** [comment]
I noticed when I reset my simulators I lost a lot of simulators.

**Comment by pedro380085** [comment]
Did you read the confirmation message?
ᐧ

On Wed, Sep 23, 2015 at 10:06 AM, Ged2323 <notifications@github.com> wrote:

> I noticed when I reset my simulators I lost a lot of simulators.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KrauseFx/snapshot/issues/198#issuecomment-142593267>.
>



-- 
Pedro Góes,
C.E.O. @ InEvent <http://inevent.us/>
Skype: pedro380085
T: +55 16 981406550

**Comment by kohtenko** [comment]
I also got this issue. Solved by opening in iOS simulator `Hardware->Device->Manage Devices`. In open menu on left panel you can review all of available simulators. In my case there was duplicates of `iPhone 6` and `iPhone 6plus`. Remove duplicates and run `snapshot` again

**Comment by PaulTaykalo** [comment]
@kohtenko Thanks :+1:

**Comment by yogoo** [comment]
Same issue with Xcode 7.0.1. @kohtenko solution led to a different error. The workaround was to configure all devices to the "s" version in the ```Snapfile```: ```iPhone 6s```, ```iPhone 6s Plus```,...

**Comment by humberaquino** [comment]
@joepasq workaround worked for me. Added the "-watch" suffix to the device name that I wanted to create the snapshot from, then create a new simulator without a paired apple watch.
@KrauseFx Could "the way to fetch a list of available devices" that you mentioned be this one?
`instruments -s devices`

**Comment by cbowns** [comment]
Another workaround which worked for me: delete the 9.0 + Apple Watch simulator, and manually add one without a Watch.

**Comment by billypchan** [comment]
@cbowns How to remove the 9.0 + Apple Watch simulator?

**Comment by cbowns** [comment]
some quick unedited screenshots:

Step 1: go to Devices

![screen shot 2015-10-15 at 9 47 01 am](https://cloud.githubusercontent.com/assets/474/10520937/dac61726-7321-11e5-94f0-949aa94cf11b.png)

Step 2: Scroll down in the left sidebar:

![screen shot 2015-10-15 at 9 47 05 am](https://cloud.githubusercontent.com/assets/474/10520945/e3f759b8-7321-11e5-91be-3b75dcf55fbd.png)
![screen shot 2015-10-15 at 9 47 07 am](https://cloud.githubusercontent.com/assets/474/10520944/e3f6d24a-7321-11e5-8e1b-370ef8ecc501.png)

Step 3. Select the iPhone 6 running 9.0; it'll look something like this: (mine is named differently than yours since I deleted the default one from Xcode, but the Paired Watch info is the same)

![screen shot 2015-10-15 at 9 47 54 am](https://cloud.githubusercontent.com/assets/474/10520955/ef66518c-7321-11e5-8769-58c2ae4638d4.png)

Step 4. Delete that device.

Step 5. Add a new simulator (select the + button at the bottom left of the Devices window

Step 6. Make a new iPhone 6, without a watch:

![screen shot 2015-10-15 at 9 49 53 am](https://cloud.githubusercontent.com/assets/474/10520986/234892da-7322-11e5-8e58-e95e66ce145a.png)

**Comment by jaroslavas** [comment]
@cbowns Thanks, that worked for me!

**Comment by converted2mac** [comment]
Having this issue, but my only "duplicate" simulators are the iPhone 6 running iOS 8.4 and the iPhone 6 running iOS 9.0. The script doesn't have any issues if I explicitly tell it to snapshot the 8.4 simulators, but runs into this problem when I comment out the iOS version (or set it to try iOS 9.0). 

In my case, I don't have "duplicates" so much as I have two different simulators for the same device, running two different OSes... which is a valid use case.

**Comment by johnboiles** [comment]
@yogoo: super clever workaround since the 's' devices don't seem to have watch versions. Love it! ❤️
