### ISSUE TITLE
custom_build_args Support

### ISSUE THREAD

**Issue by pedro380085** [fastlane/snapshot#241]
Hi @KrauseFx,

On snapshot previous version, I used `custom_build_args` so I could identify when SNAPSHOT was running:

```
#ifdef SNAPSHOT
    // Do something
#else
    // Do something else
    ...
#endif
```

How can I do this now?

**Comment by larryonoff** [comment]
@pedro380085 thank yo for the issue. I have the same issue.

**Comment by yeradis** [comment]
*I need this too!*

I prefer preprocessor directives , a solution can the use of environment variables
but with the preprocessor all that code only used in SNAPSHOT is not included in the app for distribution

**Comment by ConfusedVorlon** [comment]
I'm not sure that custom build args are even necessary. I think that just setting FASTLANE_SNAPSHOT for all projects would do the job.

My impression is that most or all requests just want a way to cheat their code with 

#ifdef FASTLANE_SNAPSHOT
#endif

I don't think there is any downside to imposing that on all projects.

**Comment by johnboiles** [comment]
+1 I used `custom_build_args` as well.

Some sort of runtime or compiletime check would be nice. Though I suppose I could add an environment variable to my UITests scheme.

**Comment by johnboiles** [comment]
I added an environment variable to my UITest scheme, but it wouldn't get picked up in the app. It turns out `XCUITest`s are run as a separate process from the app, so any environment variables get passed into the test runner, but not the app itself. To see this for yourself, set a breakpoint while running your UITests and you'll see two processes in the `Debug navigator` pane in Xcode. This is pretty different from normal `XCTest`s which are a bundle that gets injected and is executed from the same process as the host app.

I'm still working on a solution, possibly something with setting `XCUIApplication`'s `launchEnvironment` at runtime.

**Comment by timbueno** [comment]
+1 on the custom_build_args.

For me this could be even be solved with a default FASTLANE_SNAPSHOT value being set by snapshot itself.

**Comment by pedro380085** [comment]
https://github.com/fastlane/snapshot/pull/284
