### ISSUE TITLE
Is it feasible to use snapshot with KIFF test?

### ISSUE THREAD

**Issue by varmeh** [fastlane/snapshot#395]

**Comment by vpolouchkine** [comment]
Are you referring to https://github.com/kif-framework/KIF?

**Comment by varmeh** [comment]
Yes.

**Comment by vpolouchkine** [comment]
That is not currently supported.

**Comment by lottadot** [comment]
I was experimenting with this recently. I haven’t found a solution yet. But I’ll explain what we were going after, and why:

1. Snapshot requires iOS9
2. KIF tests can run tests in iOS8/9 Simulators.
3. KIF only screenshots on failure.
4. Snapshot’s snapshot() function, as well as it’s ability to save them off with device/OS/language is quite handy. For us, we want the screenshots in all device formats that the app can run, in all languages, in all OS’s the app can run. Our limitation is Snapshot w/ iOS8 :(

I patched our local KIF clone to allow a screenshot function that doesn’t require failure. That mimics Snapshot’s functionality.

But that doesn’t solve everything, because Snapshot still requires the iOS9++ simulator (because it uses XCUIApplication, via it’s “SnapshotHelper.swift” to control the language the TestHost is started with).

At the moment, I’m considering an alternative Target that has a deployment target of only iOS9. The acceptance tests target would use this target to run against. That would let snapshot run. And I *think* it would let us write the tests with KIF. It would not give us screenshots of runs in the iOS8 simulator, however :( I’ve not had time to experiment further.

**Comment by varmeh** [comment]
That sounds like a cool hack.
Even if KIF Screenshot works only with iOS 9+. Could you share the hack?
